/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedNetlowRouteImport } from './routes/_authenticated/netlow'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedNetlowIndexRouteImport } from './routes/_authenticated/netlow.index'
import { Route as AuthenticatedNetlowChallengesRouteImport } from './routes/_authenticated/netlow.challenges'
import { Route as AuthenticatedNetlowCompanyRouteImport } from './routes/_authenticated/netlow.company'
import { Route as AuthenticatedNetlowDocumentsRouteImport } from './routes/_authenticated/netlow.documents'
import { Route as AuthenticatedNetlowIntegrationsRouteImport } from './routes/_authenticated/netlow.integrations'
import { Route as AuthenticatedNetlowLogRouteImport } from './routes/_authenticated/netlow.log'
import { Route as AuthenticatedNetlowReportsRouteImport } from './routes/_authenticated/netlow.reports'
import { Route as AuthenticatedNetlowReviewRouteImport } from './routes/_authenticated/netlow.review'
import { Route as ApiPublicBaselineInsightsRouteImport } from './routes/api/public/baseline-insights'
import { Route as ApiPublicHooksNetlowIngestRouteImport } from './routes/api/public/hooks/netlow-ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNetlowRoute = AuthenticatedNetlowRouteImport.update({
  id: '/netlow',
  path: '/netlow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNetlowIndexRoute =
  AuthenticatedNetlowIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowChallengesRoute =
  AuthenticatedNetlowChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowCompanyRoute =
  AuthenticatedNetlowCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowDocumentsRoute =
  AuthenticatedNetlowDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowIntegrationsRoute =
  AuthenticatedNetlowIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowLogRoute = AuthenticatedNetlowLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedNetlowRoute,
} as any)
const AuthenticatedNetlowReportsRoute =
  AuthenticatedNetlowReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const AuthenticatedNetlowReviewRoute =
  AuthenticatedNetlowReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedNetlowRoute,
  } as any)
const ApiPublicBaselineInsightsRoute =
  ApiPublicBaselineInsightsRouteImport.update({
    id: '/api/public/baseline-insights',
    path: '/api/public/baseline-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNetlowIngestRoute =
  ApiPublicHooksNetlowIngestRouteImport.update({
    id: '/api/public/hooks/netlow-ingest',
    path: '/api/public/hooks/netlow-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/netlow': typeof AuthenticatedNetlowRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/netlow/challenges': typeof AuthenticatedNetlowChallengesRoute
  '/netlow/company': typeof AuthenticatedNetlowCompanyRoute
  '/netlow/documents': typeof AuthenticatedNetlowDocumentsRoute
  '/netlow/integrations': typeof AuthenticatedNetlowIntegrationsRoute
  '/netlow/log': typeof AuthenticatedNetlowLogRoute
  '/netlow/reports': typeof AuthenticatedNetlowReportsRoute
  '/netlow/review': typeof AuthenticatedNetlowReviewRoute
  '/api/public/baseline-insights': typeof ApiPublicBaselineInsightsRoute
  '/netlow/': typeof AuthenticatedNetlowIndexRoute
  '/api/public/hooks/netlow-ingest': typeof ApiPublicHooksNetlowIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/netlow/challenges': typeof AuthenticatedNetlowChallengesRoute
  '/netlow/company': typeof AuthenticatedNetlowCompanyRoute
  '/netlow/documents': typeof AuthenticatedNetlowDocumentsRoute
  '/netlow/integrations': typeof AuthenticatedNetlowIntegrationsRoute
  '/netlow/log': typeof AuthenticatedNetlowLogRoute
  '/netlow/reports': typeof AuthenticatedNetlowReportsRoute
  '/netlow/review': typeof AuthenticatedNetlowReviewRoute
  '/api/public/baseline-insights': typeof ApiPublicBaselineInsightsRoute
  '/netlow': typeof AuthenticatedNetlowIndexRoute
  '/api/public/hooks/netlow-ingest': typeof ApiPublicHooksNetlowIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/netlow': typeof AuthenticatedNetlowRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/netlow/challenges': typeof AuthenticatedNetlowChallengesRoute
  '/_authenticated/netlow/company': typeof AuthenticatedNetlowCompanyRoute
  '/_authenticated/netlow/documents': typeof AuthenticatedNetlowDocumentsRoute
  '/_authenticated/netlow/integrations': typeof AuthenticatedNetlowIntegrationsRoute
  '/_authenticated/netlow/log': typeof AuthenticatedNetlowLogRoute
  '/_authenticated/netlow/reports': typeof AuthenticatedNetlowReportsRoute
  '/_authenticated/netlow/review': typeof AuthenticatedNetlowReviewRoute
  '/api/public/baseline-insights': typeof ApiPublicBaselineInsightsRoute
  '/_authenticated/netlow/': typeof AuthenticatedNetlowIndexRoute
  '/api/public/hooks/netlow-ingest': typeof ApiPublicHooksNetlowIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/netlow'
    | '/blog/$slug'
    | '/blog/'
    | '/netlow/challenges'
    | '/netlow/company'
    | '/netlow/documents'
    | '/netlow/integrations'
    | '/netlow/log'
    | '/netlow/reports'
    | '/netlow/review'
    | '/api/public/baseline-insights'
    | '/netlow/'
    | '/api/public/hooks/netlow-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog/$slug'
    | '/blog'
    | '/netlow/challenges'
    | '/netlow/company'
    | '/netlow/documents'
    | '/netlow/integrations'
    | '/netlow/log'
    | '/netlow/reports'
    | '/netlow/review'
    | '/api/public/baseline-insights'
    | '/netlow'
    | '/api/public/hooks/netlow-ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/netlow'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/netlow/challenges'
    | '/_authenticated/netlow/company'
    | '/_authenticated/netlow/documents'
    | '/_authenticated/netlow/integrations'
    | '/_authenticated/netlow/log'
    | '/_authenticated/netlow/reports'
    | '/_authenticated/netlow/review'
    | '/api/public/baseline-insights'
    | '/_authenticated/netlow/'
    | '/api/public/hooks/netlow-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicBaselineInsightsRoute: typeof ApiPublicBaselineInsightsRoute
  ApiPublicHooksNetlowIngestRoute: typeof ApiPublicHooksNetlowIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/netlow': {
      id: '/_authenticated/netlow'
      path: '/netlow'
      fullPath: '/netlow'
      preLoaderRoute: typeof AuthenticatedNetlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/netlow/': {
      id: '/_authenticated/netlow/'
      path: '/'
      fullPath: '/netlow/'
      preLoaderRoute: typeof AuthenticatedNetlowIndexRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/challenges': {
      id: '/_authenticated/netlow/challenges'
      path: '/challenges'
      fullPath: '/netlow/challenges'
      preLoaderRoute: typeof AuthenticatedNetlowChallengesRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/company': {
      id: '/_authenticated/netlow/company'
      path: '/company'
      fullPath: '/netlow/company'
      preLoaderRoute: typeof AuthenticatedNetlowCompanyRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/documents': {
      id: '/_authenticated/netlow/documents'
      path: '/documents'
      fullPath: '/netlow/documents'
      preLoaderRoute: typeof AuthenticatedNetlowDocumentsRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/integrations': {
      id: '/_authenticated/netlow/integrations'
      path: '/integrations'
      fullPath: '/netlow/integrations'
      preLoaderRoute: typeof AuthenticatedNetlowIntegrationsRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/log': {
      id: '/_authenticated/netlow/log'
      path: '/log'
      fullPath: '/netlow/log'
      preLoaderRoute: typeof AuthenticatedNetlowLogRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/reports': {
      id: '/_authenticated/netlow/reports'
      path: '/reports'
      fullPath: '/netlow/reports'
      preLoaderRoute: typeof AuthenticatedNetlowReportsRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/_authenticated/netlow/review': {
      id: '/_authenticated/netlow/review'
      path: '/review'
      fullPath: '/netlow/review'
      preLoaderRoute: typeof AuthenticatedNetlowReviewRouteImport
      parentRoute: typeof AuthenticatedNetlowRoute
    }
    '/api/public/baseline-insights': {
      id: '/api/public/baseline-insights'
      path: '/api/public/baseline-insights'
      fullPath: '/api/public/baseline-insights'
      preLoaderRoute: typeof ApiPublicBaselineInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/netlow-ingest': {
      id: '/api/public/hooks/netlow-ingest'
      path: '/api/public/hooks/netlow-ingest'
      fullPath: '/api/public/hooks/netlow-ingest'
      preLoaderRoute: typeof ApiPublicHooksNetlowIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedNetlowRouteChildren {
  AuthenticatedNetlowChallengesRoute: typeof AuthenticatedNetlowChallengesRoute
  AuthenticatedNetlowCompanyRoute: typeof AuthenticatedNetlowCompanyRoute
  AuthenticatedNetlowDocumentsRoute: typeof AuthenticatedNetlowDocumentsRoute
  AuthenticatedNetlowIntegrationsRoute: typeof AuthenticatedNetlowIntegrationsRoute
  AuthenticatedNetlowLogRoute: typeof AuthenticatedNetlowLogRoute
  AuthenticatedNetlowReportsRoute: typeof AuthenticatedNetlowReportsRoute
  AuthenticatedNetlowReviewRoute: typeof AuthenticatedNetlowReviewRoute
  AuthenticatedNetlowIndexRoute: typeof AuthenticatedNetlowIndexRoute
}

const AuthenticatedNetlowRouteChildren: AuthenticatedNetlowRouteChildren = {
  AuthenticatedNetlowChallengesRoute: AuthenticatedNetlowChallengesRoute,
  AuthenticatedNetlowCompanyRoute: AuthenticatedNetlowCompanyRoute,
  AuthenticatedNetlowDocumentsRoute: AuthenticatedNetlowDocumentsRoute,
  AuthenticatedNetlowIntegrationsRoute: AuthenticatedNetlowIntegrationsRoute,
  AuthenticatedNetlowLogRoute: AuthenticatedNetlowLogRoute,
  AuthenticatedNetlowReportsRoute: AuthenticatedNetlowReportsRoute,
  AuthenticatedNetlowReviewRoute: AuthenticatedNetlowReviewRoute,
  AuthenticatedNetlowIndexRoute: AuthenticatedNetlowIndexRoute,
}

const AuthenticatedNetlowRouteWithChildren =
  AuthenticatedNetlowRoute._addFileChildren(AuthenticatedNetlowRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNetlowRoute: typeof AuthenticatedNetlowRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNetlowRoute: AuthenticatedNetlowRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicBaselineInsightsRoute: ApiPublicBaselineInsightsRoute,
  ApiPublicHooksNetlowIngestRoute: ApiPublicHooksNetlowIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
